# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - youdesignone

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_a31b4125a21d4b349c0d839e14581a06 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_cba42305a99341868b0bbdc36b940684 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_a31b4125a21d4b349c0d839e14581a06 }}/xyzmn/azure:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'youdesignone'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d733f95699534125b5bc5dc36854d60c }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_a31b4125a21d4b349c0d839e14581a06 }}/xyzmn/azure:${{ github.sha }}'